version: '3'

networks:
  core-infra:
    external: true

services:
  keycloak:
      image: fnext/keycloak:0.0.1
      environment:
        DB_VENDOR: h2
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
      volumes:
        - /nfs/docker/keycloak/data:/opt/jboss/keycloak/standalone/data
      networks:
       - core-infra
      ports:
        - 8081:8080
      deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints:
            - "node.hostname == fnext-padellion"